### ISSUE TITLE
Can not share my presence

### ISSUE THREAD

**Issue by FlickySH** [MinnDevelopment/Java-DiscordRPC#22]
Made a simple Console app RPC, It works for me but not for everyone else, whitelisted my friend in the project page, but still not working for him

**Comment by m-sterling** [comment]
Can you elaborate on this? What exactly prevents you from "sharing your presence?" How are you using the library that causes this issue?

**Comment by FlickySH** [comment]
That was fast
Editing
Was a mistake of sending it empty

**Comment by FlickySH** [comment]
It should be clear now

**Comment by m-sterling** [comment]
Thank you for providing more information. Could you possibly attach some of the code you're using? Thanks in advance.

**Comment by FlickySH** [comment]
Yes, but its Kotlin, can you understand it?

**Comment by m-sterling** [comment]
Yes.

**Comment by FlickySH** [comment]
https://gist.github.com/Aregev2/17a1ce8604172719672e4cb34c3d4ebd
There you go.

**Comment by FlickySH** [comment]
O WAIT
Wrong lib
Do not check that, Im sorry, It was from another repo
@kkirigaya

**Comment by m-sterling** [comment]
I believe the issue is that you're using an application ID that isn't "approved" by Hammer & Chisel, and therefore users other than the one who created said application cannot use it. If you want someone else to use the application, you'll have to either submit it to be approved by H&C (which will no doubt be denied as you're just messing with RPC), use an approved ID (such as the one used in H&C's [send-presence.c](https://github.com/discordapp/discord-rpc/blob/master/examples/send-presence/send-presence.c) RPC example), or have them create an application themselves.

**Comment by FlickySH** [comment]
https://github.com/Vatuu/discord-rpc
I used this
Sorry for disturbing

**Comment by FlickySH** [comment]
@kkirigaya But then I do not have control over the presence (name and assets),

**Comment by MinnDevelopment** [comment]
@kkirigaya there is no such thing as "approved" application id's. Discord offers a whitelist to enable global access to "Ask to Join" and "Spectate" for your application, however anyone may use it as they please.

**Comment by m-sterling** [comment]
@MinnDevelopment Ah, you're right, I got confused. My bad! Thanks for clarifying it for me.

@Aregev2 Aside from testing RPC, the presence is supposed to be set programmatically, for example, when a user enters a match or starts a game. If *you* want control over the presence rather than the user, you'll have to set it up to programmatically set the state, details, etc.

Regardless, Vatuu's lib was being used when this issue was made, so none of this really applies here. 😄
