### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by jm02394** [MinnDevelopment/Java-DiscordRPC#24]
Sorry if this is a stupid question, but when I try to load it, it says that it cannot find the module "discord-rpc" and crashes. Any help would be greatly appreciated.

**Comment by m-sterling** [comment]
Do you have a more verbose error? And is this in a development environment or are you using an application that uses this library? If it's a development environment, please show how you're using the library. Thanks in advance!

**Comment by jm02394** [comment]
Never mind, I found a solution. I included the full path to the .dll, and that solved the problem.

**Comment by jm02394** [comment]
That was only a temporary solution, and now I am trying to actually build my program. I am using Eclipse, and my src/main/resources looks like this: 
![image](https://user-images.githubusercontent.com/34775545/41010401-099acd4a-68ec-11e8-8cf4-e51fa7e6ae4c.png)
I have tried everything, and I don't know how to fix it. Again, sorry if this is a stupid question, I am not good with Java. If you have any other questions, feel free to ask me. Thanks!

**Comment by MinnDevelopment** [comment]
@Poipt have you figured out a solution for your problem? I recommend using the artifact provided through jcenter rather than trying to compile it yourself.

Edit: I have also published a release for v2.0.1 with jars that should be usable for projects not using gradle/maven or equivalents. For this you should use the jar containing all dependencies [`java-discord-rpc-2.0.1-all.jar`](https://github.com/MinnDevelopment/java-discord-rpc/releases/download/v2.0.1/java-discord-rpc-2.0.1-all.jar) and the sources jar (for documentation). I do recommend to use gradle instead, however.

**Comment by jm02394** [comment]
Oh, shoot. Yeah, I figured this out a while ago and forgot to close it. I fixed it by getting the dll from the web using `FileUtils.copyURLToFile(new URL("https://github.com/MinnDevelopment/discord-rpc-release/blob/master/src/main/resources/win32-x86-64/discord-rpc.dll?raw=true"), file);`, but thanks anyways!

**Comment by m-sterling** [comment]
Hey Poipt, glad you resolved this issue. I'd just like to recommend that you use RawGit to pull individual files from the repo. IIRC RawGit supports caching and has a higher ratelimit than GitHub. 

Cheers!
