### ISSUE TITLE
[Error/Bug] MacOS Error Loading dll (Code Signature Invalid)

### ISSUE THREAD

**Issue by CDAGaming** [MinnDevelopment/Java-DiscordRPC#27]
Reference: https://github.com/discordapp/discord-rpc/issues/170

When trying to load the dll/dylib, this error occurs:
https://gist.github.com/CDAGaming/f5e5bae7fd5f50a0d1da1fc3933fe026

**Comment by MinnDevelopment** [comment]
Please provide more details, such as

- Your platform and OS version
- How you load the library
- How you setup your runtime
- Your version of this library
- Your version of the releases (discord-rpc-release dependency)

**Comment by paulhobbel** [comment]
From what I can see from the error log the issue is that you did not use the original files discord provided on their GitHub Releases page for Discord RPC. The error is an signing issue, I suggest you try it again but this time with the original files from here: https://github.com/discordapp/discord-rpc/releases

**Comment by MinnDevelopment** [comment]
This library uses the released binaries by discord as a dependency through gradle.

**Comment by paulhobbel** [comment]
I know your library does, however he is not using the resources of your library, hence the crash. As far as I know the issue at his end is now resolved

**Comment by CDAGaming** [comment]
Closing as Fixed, from @ItsDizzy s Solution. Whoops!
