### ISSUE TITLE
This is less of an issue and more of something i want to know

### ISSUE THREAD

**Issue by withinq** [MinnDevelopment/Java-DiscordRPC#41]
I want to change the icon displayed while playing a custom modpack I am working on. I didn't know where to ask so I thought I could ask here

**Comment by m-sterling** [comment]
In order to change the icons shown in the Rich Presence popup, you need to first add the icons in the [Discord developer portal](http://discordapp.com/developers/applications/) for your app, then change the [`largeImageKey`](https://github.com/MinnDevelopment/java-discord-rpc/blob/1fc69b1fff4938e7bcf6cfde3d62627ea6bf6498/src/main/java/club/minnced/discord/rpc/DiscordRichPresence.java#L112) and [`smallImageKey`](https://github.com/MinnDevelopment/java-discord-rpc/blob/1fc69b1fff4938e7bcf6cfde3d62627ea6bf6498/src/main/java/club/minnced/discord/rpc/DiscordRichPresence.java#L128) before pushing the new presence with [`Discord_UpdatePresence`](https://github.com/MinnDevelopment/java-discord-rpc/blob/1fc69b1fff4938e7bcf6cfde3d62627ea6bf6498/src/main/java/club/minnced/discord/rpc/DiscordRPC.java#L114).

Please let me know if you need any further explanation. :)
